# Per environment values which override defaults in hmpps-dpr-tools-api/values.yaml

generic-service:
  serviceAccountName: "dpr-tools-development-cross-iam"

  ingress:
    host: dpr-tools-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_TOOLS_USER
    ME_CASELOADS_API_HOST: https://nomis-user-roles-api-dev.prison.service.justice.gov.uk
    URL_ENV_SUFFIX: dev
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-development
    REDSHIFT_DATA_DB: datamart
    REDSHIFT_DATA_ROLE_ARN: arn:aws:iam::771283872747:role/dpr-data-api-cross-account-role
    REDSHIFT_DATA_S3_LOCATION: dpr-working-development/reports

  allowlist:
    groups:
      - circleci
      - internal

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-digital-prison-reporting-dev
