---
# Per environment values which override defaults in hmpps-dpr-tools-api/values.yaml

generic-service:
  ingress:
    host: dpr-tools-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    REDSHIFT_JDBC_URL: jdbc:redshift://dpr-redshift-preproduction.c1q5ypu1uv3q.eu-west-2.redshift.amazonaws.com:5439/datamart
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_TOOLS_USER
    ME_CASELOADS_API_HOST: https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-digital-prison-reporting-preprod
